### PR TITLE
Cyclecloud:GPU experiments

### PR DESCRIPTION
**Pull request by amarathe84**
WIP on adding Cyclecloud GPU experiment SLURM scripts. Will continue to update the description based on progress.

Applications tested: 
- Kripke

### CODE REVIEW

**Comment by vsoch** [comment]
Can you please tell (ping/at) me when this is ready for review? Ty!

**Comment by vsoch** [comment]
@amarathe84 is this ready for review?

**Comment by amarathe84** [comment]
Yes, it's ready for review--removed WIP.

**Comment by amarathe84** [comment]
> @amarathe84 is this ready for review?

@vsoch Yes it's ready for review--removed WIP from title.

**Pull request merged**
